version: '3'
services:
  dokuwiki:
    image: linuxserver/dokuwiki:latest
    container_name: dokuwiki
    ports:
      - "8081:80"
    volumes:
      - ./conf:/config/dokuwiki/conf
      - ./data:/config/dokuwiki/data
    environment:
      - PHP_TZ=UTC
    restart: always
