# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 09 Dec 2024 07:47:19 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$t4aNK1YBWzdmnXzLOsHe4OW3aGEJn/UjObcp71vVUvN7qQur/PdHm:Admin:admin@gmail.com:admin,user
